language: node_js

node_js:
  - 18.16.0

services:
  - docker

env:
  - COMMIT_NO=$(git rev-parse --short HEAD)

script:
  - docker build -t "$DOCKER_USERNAME/dokimion:$COMMIT_NO" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME/dokimion:$COMMIT_NO"

branches:
  only:
    - main
